// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Swlh.WebApp.Context;

#nullable disable

namespace Swlh.WebApp.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20250404033525_AddRelationshipForCommentOnPost")]
    partial class AddRelationshipForCommentOnPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessedAcount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.CommentOnPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostId");

                    b.ToTable("CommentOnPost");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.CommentOnWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("WordId");

                    b.ToTable("CommentOnWord");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.CommentOnWordReaction", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentOnWordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.HasKey("AccountId", "CommentOnWordId");

                    b.HasIndex("CommentOnWordId");

                    b.ToTable("CommentOnWordReaction");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.Example", b =>
                {
                    b.Property<string>("Korean")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Vietnamese")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Korean", "Vietnamese");

                    b.ToTable("Example");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.PostTag", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PostId", "Tag");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MeaningKr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeaningVn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pronunciation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WordKr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WordVn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Word");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.CommentOnPost", b =>
                {
                    b.HasOne("Swlh.WebApp.Domain.Entities.Account", "Account")
                        .WithMany("CommentOnPosts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Swlh.WebApp.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.CommentOnWord", b =>
                {
                    b.HasOne("Swlh.WebApp.Domain.Entities.Account", "Account")
                        .WithMany("CommentOnWords")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Swlh.WebApp.Domain.Entities.Word", "Word")
                        .WithMany("CommentOnWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.CommentOnWordReaction", b =>
                {
                    b.HasOne("Swlh.WebApp.Domain.Entities.Account", "Account")
                        .WithMany("CommentOnWordReactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Swlh.WebApp.Domain.Entities.CommentOnWord", "CommentOnWord")
                        .WithMany("CommentOnWordReactions")
                        .HasForeignKey("CommentOnWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("CommentOnWord");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.Post", b =>
                {
                    b.HasOne("Swlh.WebApp.Domain.Entities.Account", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.PostTag", b =>
                {
                    b.HasOne("Swlh.WebApp.Domain.Entities.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.Account", b =>
                {
                    b.Navigation("CommentOnPosts");

                    b.Navigation("CommentOnWordReactions");

                    b.Navigation("CommentOnWords");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.CommentOnWord", b =>
                {
                    b.Navigation("CommentOnWordReactions");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("Swlh.WebApp.Domain.Entities.Word", b =>
                {
                    b.Navigation("CommentOnWords");
                });
#pragma warning restore 612, 618
        }
    }
}
